FROM ubuntu:22.04
RUN apt update
RUN apt install -y openjdk-11-jdk wget
RUN apt install unzip
RUN wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip
RUN unzip fastqc_v0.11.9.zip
